import assert from 'node:assert/strict';
import {locationCheck,validatePhotos,evidenceLabel,canViewPhoto} from '../lib/evidence';
const site={latitude:30.0031455,longitude:30.9669285,radius:100};
const here={latitude:site.latitude,longitude:site.longitude,accuracy:15,timestamp:Date.now()};
assert.equal(locationCheck(here,site).ok,true);
assert.equal(locationCheck({...here,latitude:here.latitude+.002},site).ok,false);
assert.equal(locationCheck({...here,accuracy:51},site).ok,false);
assert.equal(locationCheck({...here,accuracy:-1},site).ok,false);
assert.equal(locationCheck({...here,timestamp:Date.now()-180000},site).ok,false);
assert.equal(locationCheck({...here,timestamp:Date.now()+180000},site).ok,false);
assert.equal(locationCheck({...here,latitude:NaN},site).ok,false);
assert.equal(locationCheck({...here,longitude:200},site).ok,false);
assert.equal(validatePhotos([]),null);
assert.equal(validatePhotos(undefined),null);
assert.ok(validatePhotos([{}, {}, {}, {}]));
assert.ok(validatePhotos([{category:'turf',caption:'Observed turf',data:'data:image/svg+xml;base64,PHN2Zz4='}]));
assert.ok(validatePhotos([{category:'turf',caption:'x',data:'data:image/jpeg;base64,AAAA'}]));
assert.ok(validatePhotos([{category:'turf',caption:'Observed turf',data:'data:image/jpeg;base64,'+btoa('not a JPEG image'.repeat(30))}]));
assert.equal(evidenceLabel(false,false),'Self-reported');
assert.equal(evidenceLabel(true,false),'Location checked');
assert.equal(evidenceLabel(false,true),'Photo supported');
assert.equal(evidenceLabel(true,true),'Location + photo supported');
assert.equal(canViewPhoto('player','other','author','pending','published'),false);
assert.equal(canViewPhoto('player','other','author','accepted','pending'),false);
assert.equal(canViewPhoto('player','other','author','rejected','published'),false);
assert.equal(canViewPhoto('player','other','author','accepted','published'),true);
assert.equal(canViewPhoto('player','author','author','pending','pending'),true);
assert.equal(canViewPhoto('owner','admin','author','pending','pending'),true);
console.log('24 evidence checks passed.');
