'use client';
import {useState,type FormEvent} from 'react';
import {Plus,MapPin,ExternalLink,CheckCircle2} from 'lucide-react';
import type {Venue,Court} from '../lib/data';
type DraftCourt={id?:string;name:string;type:string};
type Props={venues:Venue[];courts:Court[];sites:{venue_id:string;latitude:number;longitude:number;radius:number}[];onSaved:()=>Promise<void>;onOpen:(id:string)=>void};
export default function VenueManager({venues,courts,sites,onSaved,onOpen}:Props){
 const [selected,setSelected]=useState(''),[name,setName]=useState(''),[area,setArea]=useState(''),[facilities,setFacilities]=useState(''),[mapUrl,setMapUrl]=useState(''),[bookingUrl,setBookingUrl]=useState(''),[notes,setNotes]=useState(''),[draftCourts,setDraftCourts]=useState<DraftCourt[]>([{name:'Court 1',type:'Outdoor'}]),[latitude,setLatitude]=useState(''),[longitude,setLongitude]=useState(''),[radius,setRadius]=useState('100'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 function choose(id:string){const v=venues.find(v=>v.id===id),pin=sites.find(s=>s.venue_id===id);setSelected(id);setName(v?.name??'');setArea(v?.area??'');setFacilities(v?.facilities.join(', ')??'');setMapUrl(v?.mapUrl??'');setBookingUrl(v?.bookingUrl??'');setNotes(v?.notes??'');setDraftCourts(v?courts.filter(c=>c.venueId===id).map(c=>({id:c.id,name:c.name,type:c.type})):[{name:'Court 1',type:'Outdoor'}]);setLatitude(pin?String(pin.latitude):'');setLongitude(pin?String(pin.longitude):'');setRadius(pin?String(pin.radius):'100');setSaved('');setError('');}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setSaved('');try{
  if((latitude.trim()&&!longitude.trim())||(!latitude.trim()&&longitude.trim()))throw Error('Enter both court coordinates or leave both blank.');
  const body={venueId:selected||undefined,name,area,facilities:facilities.split(',').map(f=>f.trim()).filter(Boolean),notes,mapUrl:mapUrl.trim(),bookingUrl:bookingUrl.trim(),courts:draftCourts,location:latitude.trim()&&longitude.trim()?{latitude:Number(latitude),longitude:Number(longitude),radius:Number(radius)}:null};
  const r=await fetch('/api/venues',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j:any=await r.json();if(!r.ok)throw Error(j.error);await onSaved();setSelected(j.id);setDraftCourts(j.courts.filter((c:Court)=>c.venueId===j.id).map((c:Court)=>({id:c.id,name:c.name,type:c.type})));setSaved(j.id);
 }catch(e){setError(e instanceof Error?e.message:'Could not save venue.');}finally{setBusy(false)}}
 return <><div className="page-heading"><div><span className="eyebrow">DIRECTORY MANAGEMENT</span><h1>Manage venues</h1><p>Add a venue and its exact courts, or update an existing listing.</p></div><button className="secondary" disabled={busy} onClick={()=>choose('')}><Plus size={16}/>New venue</button></div>
 <form className="guide-card venue-editor" onSubmit={submit}><fieldset disabled={busy} className="venue-editor-fields"><label className="field-label">Listing<select value={selected} onChange={e=>choose(e.target.value)}><option value="">Add a new venue</option>{venues.map(v=><option key={v.id} value={v.id}>{v.name}{v.real?'':' (sample)'}</option>)}</select></label>
 <h2>{selected?'Edit venue':'New venue'}</h2><div className="field-grid"><label className="field-label">Venue name<input required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="Club or venue name"/></label><label className="field-label">Area<input required minLength={2} maxLength={100} value={area} onChange={e=>setArea(e.target.value)} placeholder="e.g. Sheikh Zayed, Giza"/></label></div>
 <label className="field-label">Google Maps link (optional)<input type="url" maxLength={2000} value={mapUrl} onChange={e=>setMapUrl(e.target.value)} placeholder="https://maps.google.com/…"/></label><label className="field-label">Booking link (optional)<input type="url" maxLength={2000} value={bookingUrl} onChange={e=>setBookingUrl(e.target.value)} placeholder="https://…"/></label><label className="field-label">Confirmed facilities (optional)<input maxLength={700} value={facilities} onChange={e=>setFacilities(e.target.value)} placeholder="Parking, changing rooms, café"/></label><p className="muted">Separate facilities with commas. Leave unknown details blank.</p><label className="field-label">Venue notes (optional)<textarea rows={3} maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Access details, operator or booking instructions…"/></label>
 <h2>Courts</h2><p>Name each court as players identify it at the venue.</p>{draftCourts.map((c,i)=><div className="court-editor-row" key={c.id??'new-'+i}><label className="field-label">Court {i+1} name<input required minLength={2} maxLength={60} value={c.name} onChange={e=>setDraftCourts(draftCourts.map((n,j)=>j===i?{...n,name:e.target.value}:n))}/></label><label className="field-label">Court {i+1} type<select value={c.type} onChange={e=>setDraftCourts(draftCourts.map((n,j)=>j===i?{...n,type:e.target.value}:n))}><option>Outdoor</option><option>Indoor</option><option>Covered</option></select></label>{!c.id&&draftCourts.length>1&&<button type="button" className="text-button" onClick={()=>setDraftCourts(draftCourts.filter((_,j)=>j!==i))}>Remove new court</button>}</div>)}<button type="button" className="secondary" disabled={draftCourts.length>=20} onClick={()=>setDraftCourts([...draftCourts,{name:'Court '+(draftCourts.length+1),type:draftCourts.at(-1)?.type??'Outdoor'}])}><Plus size={16}/>Add court</button><p className="muted">Existing courts keep their reviews and evidence when renamed.</p>
 <details className="pin-editor"><summary><MapPin size={16}/>Location check-in pin (optional)</summary><p>Use coordinates directly on the courts. A Maps link alone does not enable check-in.</p><div className="field-grid"><label className="field-label">Latitude<input type="number" step="any" min={-90} max={90} value={latitude} onChange={e=>setLatitude(e.target.value)}/></label><label className="field-label">Longitude<input type="number" step="any" min={-180} max={180} value={longitude} onChange={e=>setLongitude(e.target.value)}/></label></div><label className="field-label">Radius (metres)<input type="number" min={50} max={200} value={radius} onChange={e=>setRadius(e.target.value)}/></label><p className="muted">Leave the pin blank to keep check-in unavailable for a new venue. Existing pins remain saved.</p></details>
 {error&&<p className="form-error" role="alert">{error}</p>}{saved&&<div className="venue-save-result" role="status"><CheckCircle2 size={18}/>Venue and courts saved. <button type="button" className="text-button" onClick={()=>onOpen(saved)}>View listing <ExternalLink size={14}/></button></div>}<div className="dialog-footer"><button className="primary">{busy?'Saving…':selected?'Save changes':'Add venue and courts'}</button></div></fieldset></form></>;
}
