export type PhotoEvidence={id:string;category:string;caption:string;status:string};
export const categories=[{key:'turf',label:'Turf',weight:40},{key:'lighting',label:'Lighting',weight:20},{key:'glass',label:'Glass',weight:15},{key:'fence',label:'Fence',weight:10},{key:'net',label:'Net',weight:10},{key:'cleanliness',label:'Cleanliness',weight:5}];
export type Venue={id:string;name:string;area:string;type:string;courts:number;color:string;facilities:string[];real?:boolean;bookingUrl?:string;mapUrl?:string;notes?:string};
export type Court={id:string;venueId:string;name:string;type:string;ratings:number[];sampleCount:number;real?:boolean;issue?:string};
export type Review={id:string;user_id:string;court_id:string;played_date:string;ratings:string;text:string;status:string;created_at:string;location_checked?:boolean;photos?:PhotoEvidence[];name?:string};
export type Issue={id:string;user_id:string;court_id:string;category:string;severity:string;text:string;status:string;publication:string;created_at:string;location_checked?:boolean;photos?:PhotoEvidence[]};
export const venues:Venue[]=[{id:'east',name:'East Court Club',area:'New Cairo',type:'Outdoor',courts:4,color:'mint',facilities:['Parking','Changing rooms','Equipment rental']},{id:'riverside',name:'Riverside Padel',area:'Maadi',type:'Covered',courts:3,color:'blue',facilities:['Parking','Café']},{id:'west',name:'Westside Padel House',area:'Sheikh Zayed',type:'Indoor',courts:3,color:'sand',facilities:['Changing rooms','Equipment rental']},{id:'coast',name:'Coastline Courts',area:'Alexandria',type:'Outdoor',courts:2,color:'lavender',facilities:['Parking','Café']}];
venues.unshift({id:'aeon',name:'AEON Courtyards by Marakez',area:'6th of October, Giza',type:'Outdoor',courts:2,color:'mint',facilities:[],real:true,bookingUrl:'https://apps.apple.com/eg/app/padel-finder/id1579684009',mapUrl:'https://www.google.com/maps/dir//AEON+Padel+Courts,+Gamal+Abd+El-Nasir,+First+6th+of+October,+Giza+Governorate+3236211/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x1458576d4afc8595:0x5b689ddda82c32d0',notes:'Inside AEON and operated by AEON. Two outdoor courts, confirmed by the listing contributor. Book through Padel Finder; search for AEON in the app. The link opens the iPhone App Store listing. Non-resident access and facilities have not yet been confirmed.'});
export const courts:Court[]=venues.flatMap((v,j)=>Array.from({length:v.courts},(_,i)=>({id:`${v.id}-${i+1}`,venueId:v.id,name:`Court ${i+1}`,type:v.type,real:v.real,ratings:[4+i%2, i===1?3:4,4,4,5,4],sampleCount:v.real?0:12+j*3+i,...(v.id==='east'&&i===1?{issue:'Uneven lighting near the back glass'}:{})})));
export function fixtureScore(c:Court){if(c.real)return null;return Math.round(categories.reduce((sum,k,i)=>sum+(c.ratings[i]-1)*25*k.weight,0)/100)}
