import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),name:text('name').notNull(),role:text('role').notNull().default('player'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('one_owner').on(t.role).where(sql`role = 'owner'`)]);
import {sql} from 'drizzle-orm';
export const venueRecords=sqliteTable('venues',{id:text('id').primaryKey(),name:text('name').notNull(),area:text('area').notNull(),facilities:text('facilities').notNull()});
export const courtRecords=sqliteTable('courts',{id:text('id').primaryKey(),venueId:text('venue_id').notNull().references(()=>venueRecords.id),name:text('name').notNull(),type:text('type').notNull()},t=>[index('courts_venue').on(t.venueId)]);
export const visits=sqliteTable('visits',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),courtId:text('court_id').notNull().references(()=>courtRecords.id),playedDate:text('played_date').notNull(),verification:text('verification').notNull().default('unverified')},t=>[uniqueIndex('visit_daily').on(t.userId,t.courtId,t.playedDate)]);
export const reviews=sqliteTable('reviews',{id:text('id').primaryKey(),visitId:text('visit_id').notNull().references(()=>visits.id),userId:text('user_id').notNull().references(()=>users.id),courtId:text('court_id').notNull().references(()=>courtRecords.id),playedDate:text('played_date').notNull(),ratings:text('ratings').notNull(),text:text('text').notNull(),status:text('status').notNull().default('pending'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('review_visit').on(t.visitId),index('reviews_user').on(t.userId),index('reviews_court_status').on(t.courtId,t.status)]);
export const issues=sqliteTable('issues',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),courtId:text('court_id').notNull().references(()=>courtRecords.id),category:text('category').notNull(),severity:text('severity').notNull(),text:text('text').notNull(),status:text('status').notNull().default('open'),publication:text('publication').notNull().default('pending'),createdAt:text('created_at').notNull()},t=>[index('issues_court').on(t.courtId)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),target:text('target').notNull(),action:text('action').notNull(),reason:text('reason').notNull(),createdAt:text('created_at').notNull()});
